apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-multi-deployment.fullname" . }}-service
  namespace: ns-palonso
  labels:
    {{- include "my-multi-deployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pilarService.type }}
  ports:
    - port: {{ .Values.pilarService.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ include "my-multi-deployment.name" . }}
