version: '3.8'

services:
  app:
    build: .
    container_name: concert_app
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - my_network
       
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: concierto
    ports:
      - "3306:3306"  
    networks:
      - my_network
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_app
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:

volumes:
  db_data:
