name: Run Ansible Playbooks

on:
  workflow_dispatch:

jobs:
  run-ansible:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Ansible on Remote
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa adminuser2@172.167.143.214 'sudo apt update && sudo apt install ansible -y'

      - name: Remove existing ansible folder on Remote
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa adminuser2@172.167.143.214 '[ -d /home/adminuser/ansible ] && rm -rf /home/adminuser/ansible || echo "Directory does not exist"'

      - name: Copy Playbooks to Remote
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./ansible adminuser2@172.167.143.214:/home/adminuser/ansible

      - name: Run Backup Playbook
        env:
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa adminuser2@172.167.143.214 'ansible-playbook -i /home/adminuser/ansible/inventory.ini /home/adminuser/ansible/setup_backup.yaml -e "azure_storage_key=${AZURE_STORAGE_KEY}"'

      - name: Run Setup DB Playbook
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa adminuser2@172.167.143.214 'ansible-playbook -i /home/adminuser/ansible/inventory.ini /home/adminuser/ansible/setup_db.yaml'
