name: Run Ansible Playbooks

on:
  workflow_dispatch:

jobs:
  run-ansible:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Backup Playbook
        env:
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa adminuser@52.174.32.157 'ansible-playbook -i inventory.ini setup_backup.yaml -e "azure_storage_key=${AZURE_STORAGE_KEY}"'

      - name: Run Setup DB Playbook
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa adminuser@52.174.32.157 'ansible-playbook -i inventory.ini setup_db.yaml'
