name: Run Ansible Playbooks

on:
  workflow_dispatch:

jobs:
  run-ansible:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Generate and copy SSH key to remote
        run: |
          ssh-keygen -t rsa -b 2048 -m PEM -f ~/.ssh/id_rsa
          ssh-copy-id -i ~/.ssh/id_rsa.pub adminuser@51.145.79.188
          ssh adminuser@51.145.79.188 'chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys'

      - name: Install Ansible on Remote
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa adminuser@51.145.79.188 'sudo apt update && sudo apt install ansible -y'

      - name: Remove existing ansible folder on Remote
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa adminuser@51.145.79.188 'rm -rf /home/adminuser/ansible'

      - name: Copy Playbooks to Remote
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./ansible adminuser@51.145.79.188:/home/adminuser/ansible

      - name: Run Backup Playbook
        env:
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa adminuser@51.145.79.188 'ansible-playbook -i /home/adminuser/ansible/inventory.ini /home/adminuser/ansible/setup_backup.yaml -e "azure_storage_key=${AZURE_STORAGE_KEY}"'

      - name: Run Setup DB Playbook
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa adminuser@51.145.79.188 'ansible-playbook -i /home/adminuser/ansible/inventory.ini /home/adminuser/ansible/setup_db.yaml'
