name: CD for Application

on:
  workflow_run:
    workflows: ["CI for Application"]
    types:
      - completed

jobs:
  deploy-to-aks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Deploy to AKS
        run: kubectl apply -f kubernetes/
