name: CD for Application and K8s Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    defaults:
      run:
        shell: bash

    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout repository
        uses: actions/checkout@v2

      # Obtén la versión basada en el entorno
      - name: Get version based on environment
        id: get_version
        run: |
          if [ "${{ inputs.environment }}" == "dev" ]; then
            # Use GitHub run number for dev version
            VERSION="dev-build-${{ github.run_number }}"
            echo "ACR_NAME=${{ secrets.DEV_ACR_NAME }}" >> $GITHUB_ENV
            VALUES_FILE="values-dev.yaml"
          else
            # Use version from composer.json for prod
            VERSION=$(jq -r '.version' app/composer.json)
            echo "ACR_NAME=${{ secrets.PROD_ACR_NAME }}" >> $GITHUB_ENV
            VALUES_FILE="values-prod.yaml"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VALUES_FILE=$VALUES_FILE" >> $GITHUB_ENV

      - name: Set Azure account
        run: |
          az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP_NAME_AKS }} --name ${{ secrets.CLUSTER_NAME }} --overwrite-existing

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Install kubelogin
        run: |
          curl -Lo kubelogin.zip https://github.com/Azure/kubelogin/releases/latest/download/kubelogin-linux-amd64.zip
          unzip kubelogin.zip -d /usr/local/bin
          sudo mv /usr/local/bin/bin/linux_amd64/kubelogin /usr/local/bin/
          rm -rf kubelogin.zip /usr/local/bin/bin

      - name: Convert kubeconfig
        run: |
          kubelogin convert-kubeconfig -l azurecli

      # Desplegar la aplicación a Kubernetes usando Helm
      - name: Deploy to Kubernetes with Helm
        run: |
          if [ "${{ inputs.environment }}" == "dev" ]; then
            helm upgrade --install my-multi-deployment ./my-multi-deployment \
              --values ./my-multi-deployment/$VALUES_FILE \
              --set image.repository=${{ env.ACR_NAME }}.azurecr.io/my-concert-test \
              --set image.tag=${VERSION}
          else
            helm upgrade --install my-multi-deployment ./my-multi-deployment \
              --values ./my-multi-deployment/$VALUES_FILE \
              --set image.repository=${{ env.ACR_NAME }}.azurecr.io/my-concert-app \
              --set image.tag=${VERSION}
          fi

      # Obtener todos los recursos en el namespace
      - name: Get all resources in namespace
        run: |
          kubectl get all -n ns-palonso

      # Aplicar el Ingress Controller
      - name: Apply Ingress Controller
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.3.0/deploy/static/provider/cloud/deploy.yaml

      # Obtener pods de Ingress
      - name: Get Ingress pods
        run: |
          kubectl get pods --namespace ingress-nginx

      # Obtener servicio de Ingress
      - name: Get Ingress service
        run: |
          kubectl get service ingress-nginx-controller --namespace=ingress-nginx
