name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'terraform/**'
      - 'app/**'
  pull_request:
    branches:
      - main

jobs:
  conditional-workflow-trigger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Determina qué cambios se han realizado
      - name: Set up Path Filter
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            infra:
              - 'terraform/**'
            app:
              - 'app/**'

      - name: Set output for infra
        if: ${{ steps.filter.outputs.infra == 'true' }}
        run: echo "infra_changed=true" >> $GITHUB_ENV

      - name: Set output for app
        if: ${{ steps.filter.outputs.app == 'true' }}
        run: echo "app_changed=true" >> $GITHUB_ENV

      - name: Output environment variables
        run: |
          echo "infra_changed=${{ env.infra_changed }}"
          echo "app_changed=${{ env.app_changed }}"

  # Se ejecutan solo en dev cuando cambien los ficheros correspondientes
  trigger-ci-infra:
    needs: conditional-workflow-trigger
    if: needs.conditional-workflow-trigger.outputs.infra_changed == 'true' && github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/ci-infra.yaml
    with:
      directory: ./terraform
    secrets: inherit

  trigger-ci-app:
    needs: conditional-workflow-trigger
    if: needs.conditional-workflow-trigger.outputs.app_changed == 'true' && github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/ci.yaml
    with:
      directory: ./app
    secrets: inherit
