name: CI for Infrastructure

on:
  push:
    branches:
      - palonso-iac-b

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure environment variables
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.TENANT_ID }}" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: ./terraform

      - name: Force Unlock State
        run: terraform force-unlock ac0fae87-e9c3-1c9d-91cf-f5130070734d
        continue-on-error: true
        working-directory: ./terraform

      - name: Terraform Init Again
        run: terraform init -reconfigure
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars
        working-directory: ./terraform
