name: CI for Infrastructure

on:
  push:
    branches:
      - iac

jobs:
  terraform-plan-and-acr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Get ACR credentials
        id: acr-creds
        run: |
          ACR_PASSWORD=$(az acr credential show --name palonsoacr --query "passwords[0].value" -o tsv)
          echo "ACR_PASSWORD=$ACR_PASSWORD" >> $GITHUB_ENV

      - name: Set ACR credentials as GitHub Secrets
        run: |
          echo "::add-mask::${{ env.ACR_PASSWORD }}"
          echo "${{ env.ACR_PASSWORD }}" > /tmp/acr_password
        env:
          ACR_PASSWORD: ${{ env.ACR_PASSWORD }}
