name: CI for Application

on:
  workflow_run:
    workflows: ["CD for Infrastructure"]
    types:
      - completed

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to ACR
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login palonsoacr.azurecr.io -u "${{ secrets.ACR_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t palonsoacr.azurecr.io/my-concert-app:latest .
        working-directory: ./docker

      - name: Push Docker image
        run: docker push palonsoacr.azurecr.io/my-concert-app:latest

  setup-runner:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure runner on backup VM
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa adminuser@52.174.32.157 'bash -s' <<'EOF'
          mkdir -p actions-runner && cd actions-runner
          curl -o actions-runner-linux-x64-2.317.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
          echo "9e883d210df8c6028aff475475a457d380353f9d01877d51cc01a17b2a91161d  actions-runner-linux-x64-2.317.0.tar.gz" | shasum -a 256 -c
          tar xzf ./actions-runner-linux-x64-2.317.0.tar.gz
          ./config.sh --url https://github.com/stemdo-labs/final-project-palonso --token BHVK5FOMR5FF7NYTKKBTG5TGOF2W2
          ./run.sh
          EOF

      - name: Install Ansible
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa adminuser@52.174.32.157 'sudo apt-get update && sudo apt-get install -y ansible'
