name: CI for Application

on:
  workflow_run:
    workflows: ["CD for Infrastructure"]
    types:
      - completed

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to ACR
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login palonsoacr.azurecr.io -u "${{ secrets.ACR_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t palonsoacr.azurecr.io/my-concert-app:latest .
        working-directory: ./docker

      - name: Push Docker image
        run: docker push palonsoacr.azurecr.io/my-concert-app:latest

  setup-runner:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


      - name: Install Ansible
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa adminuser@52.174.32.157 'sudo apt-get update && sudo apt-get install -y ansible'
