name: 'Terraform Destroy'

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.client_id }}
      ARM_CLIENT_SECRET: ${{ secrets.client_secret }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.subscription_id }}
      ARM_TENANT_ID: ${{ secrets.tenant_id }}
      TF_VERSION: 1.5.7
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: 'Terraform Init'
        id: init
        run: terraform -chdir=./terraform init
        
      - name: Terraform Destroy
        run: terraform -chdir=./terraform destroy -auto-approve
