name: Update Composer Version

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to update'
        required: true
        type: string

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:
      - uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch all branches
        run: git fetch origin

      - name: Switch to main branch
        run: git checkout main

      - name: Delete local and remote dev branch
        run: |
          git branch -D dev || true
          git push origin --delete dev || true

      - name: Recreate dev branch from main
        run: git checkout -b dev origin/main

      - name: Bump version in composer.json
        run: |
          VERSION=$(jq -r '.version' app/composer.json)
          NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF += 1 ; print}')
          sed -i "s/\"version\": \"$VERSION\"/\"version\": \"$NEW_VERSION\"/" app/composer.json
          git config --global user.email "palonso@stemdo.io"
          git config --global user.name "Pilar"
          git add app/composer.json
          git commit -m "Bump version to $NEW_VERSION"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/stemdo-labs/final-project-palonso.git dev
